#!/bin/bash
cleos push action hospital.vt delpatient '[hospital.vt,conniebarrab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gracetracy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salembeeson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,corissrottge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garvintyers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wilonemcllee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gearardmcrae]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,silvabudgen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reinaldotarn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlineheeley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,issieold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joannebrall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,noraopdenort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pepillolong]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,remingtonfer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellsworthhan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,flinnpease]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teresaevetts]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katecino]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,larisacordob]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liannaodeson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vinniepavlik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kesliejudgki]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,florindacapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beatricefonz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvanmacias]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clarinemchal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,phaidrazacze]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barrondynele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,buckiecameli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sophienyland]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lylemcgreay]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zelmagirarde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tandicraiste]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,louisepearma]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jacksonrodwe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sauveurpache]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marvpohlke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murialtimny]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kittieshanno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,theowesson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grannyhalwar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nadeanworsal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,breannelithg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tillywarwick]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andipraundli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gannyboldiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruthannlegon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kathlinshack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edythemathis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farandchismo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earliemclane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garaldghiott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lesleygumbre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,albinamartyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emelialejean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pepillolong]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jorriedenisk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,breannelithg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubriepeters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,remingtonfer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestynacos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lexislegging]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pearcerosett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joannaworlan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,catheetardif]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evelinsertin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tristamsalts]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,starrgurry]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bentleybirne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashieningles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katharineant]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,heddiebernas]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juanajuliano]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stantonmctea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,osgoodbernar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cybillelvey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kittieshanno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,skyejonke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryjoadnam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestynacos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cletisgalleh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nateuvedale]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelinawemes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,conanthandre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmitdillamo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alejandrodud]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,samkrauss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barriebaigri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arabelletell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faydrastorck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adriahutton]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arnuadbelbin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,geryormond]' -p hospital.vt 
