#!/bin/bash
cleos push action hospital.vt delpatient '[hospital.vt,paulietuckwe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leelahobreen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,milogethen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,romondabrizl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sijeanequin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlynehache]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bettebattrum]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kevandarbysh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiakeran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,burchshawl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,almirewalby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,paulymcalind]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joreyfleeman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gretnachaims]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,isacsimonite]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daviddewycli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,noraopdenort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,godwinabadam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hedvigbyway]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambrosmacker]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,denysferreir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,millisentcot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chadwicknorm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,traciepaulil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,worthfaherty]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sophienyland]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,friederikelo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,regenharvatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teddiemably]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bessnealy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liefcuredell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nicolicollet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,briannemaria]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gerladinakee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,isabeldeblin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bentleybirne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,regenharvatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kenonhowle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,betsyverlind]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sherwoodcast]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arviefallanc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivamelville]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ardenchaudre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeremeroggie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,manuelrubel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gennifermirr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,skyejonke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorettaginn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,symanmoralis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clarehubball]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salliesaint]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ardrareeder]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,issieold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlynehache]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,florencebren]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,phaidrazacze]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tedmundstobb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gerladinakee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thaxterschol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joelynnmanse]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastingsnapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,albinamartyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristilenden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katharineant]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arvcrookes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marysacamill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claybournegr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beretleathwo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nateuvedale]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubriepeters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lewshaudfurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,baxterorourk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,saunchospitt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pippopottica]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorileetippe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farandchismo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pacokemmett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michelewille]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,theowesson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clercyeudall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spenceomalle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tamasfollitt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kimbracallea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michelewille]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rozelladripp]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avromsimonea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bethanneprin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,merrillpento]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lanarothchil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,audreytaggar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,corissrottge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,benjamencutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shannonhans]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teddiemably]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reuvenedgett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ozzycicerone]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garrettyearn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vivianahanha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alexiofumaga]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vinniepavlik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joelynnmanse]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,penrodcortes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enochmillan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,valmarichie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pavlovlampl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aloysiusgow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nortonyirrel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rowenagrayst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,penrodcortes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bobinedybald]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suziropkins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreashark]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastypattins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,humphreyemin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camalafurnel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alejandrodud]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,paulietuckwe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vanbarritt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doreyantosik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nadeanworsal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pavlovlampl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudettaket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,antoinettesh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,careyvancast]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mirabellacha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elainacowope]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayecastaned]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,antoinettesh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katerinaleve]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derwinoakenf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,randymaccurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elonoresepht]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sapphirakiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suttonnixon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,worthfaherty]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,candigheerha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jannelwipfle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beckahugle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ysabelketley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anamarkova]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudianshri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,parsifaldean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beliciasulta]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joryveevers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joannaworlan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avabonicelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leawyrill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donicaaubray]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avromsimonea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,staciapenlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashleyreadwi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lezleywye]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxgullan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dametomes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlichadney]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittdehmel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmalynnlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,opalinahiggo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestatejer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madalenacurs]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adobabb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreamarqui]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryjofranki]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lezleywye]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bibbiewait]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cletisgalleh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,crosbystande]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sybilbraganz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,amargomaccar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,seekeech]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suzanngeorge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlineheeley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leightonstan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,benjamencutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bethanneprin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahcompf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spenceomalle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lylemcgreay]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alfieseddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juditharocki]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,orrinrae]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vidovictrele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ariellelopez]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,briannemaria]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harriotodde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gretalsimonn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gradeykynoch]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,randymaccurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carliecuerda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beckahugle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiakeran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thelmawoods]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carliecuerda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raynellstumm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivilibbis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,giuliomarle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emelialejean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,traciepaulil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jennifercush]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lezleywye]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brynaferreo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sharaislewco]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rafaboyson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sophiedoming]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brookgarrish]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hildyrosini]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alfieseddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grettamanuea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gailclemett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcotomczyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bailiedrable]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sidneysouthe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luciosevior]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ardrareeder]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luellepetrol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,archibaldobu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alonzojemiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,delcinagrett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,papagenaspir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leighbartosi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hedwigascarl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madonnatenno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jackiechella]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grannyhalwar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,natalyaclinn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,araserot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nivenacreman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murialtimny]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubriepeters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,triskmietsch]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madeleneible]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,margapringle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,galebettis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dukiereuble]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beckahugle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kevandarbysh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tillywarwick]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelemulles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldensnape]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harlinmackle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nonislader]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,careymckirto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorettabeyne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nanineatack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,symanmoralis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ceceharverso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tatianiarutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,linneayushma]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudettaket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derrilharbar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartonandras]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ciriloprestn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlimacian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,amargomaccar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chrisbraniff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,olvanhawksle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucitapriest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murialtimny]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sewardkolush]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jasenbrayson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evynmorewood]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellsworthhan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucasdevaan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,josefaputten]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,washbaudino]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tedblaydon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalecarbr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nateuvedale]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nowellkemer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gilbertasiby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shellysheldo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebedeedorew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,duncantrollo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sosannastear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elfierenne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aniashillida]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raquelabeswe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eadaglencros]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melindaterne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmitdillamo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anamarkova]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claysonoldme]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shaylynnhunt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,seanmcgee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,estrellagirs]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avismerioth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodgewilmott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alonzojemiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cindapipkin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gretalsimonn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berniewinspa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marksweeting]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kevandarbysh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernyblaszcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tytrewhela]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reamonnshawy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hildyrosini]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestyndeni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wesleyhrihor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daisiloudian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,norriehaybal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lesliemathwe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,burkrosenbus]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,feygilbee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cortylawie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubriepeters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristinadepi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wandiecourag]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kellyceeley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nowellkemer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlineheeley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,simonyearsle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loneelaphorn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dolliecallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,silvabudgen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebedeedorew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassiemcgee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,conanthandre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sylasgraser]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robbincossan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derwardchaff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katerinaleve]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wesleyhrihor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nortonyirrel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylinsenec]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pacokemmett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ansontolputt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,watbaldi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jaynemazzia]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juietacollin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,annadianenic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,galinalantif]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sonnyblackmo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahcompf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,opalinahiggo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tallielansda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sayrecunning]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clarettarave]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayleyschwan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elwirawines]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubreychuck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalliddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fleurkitteri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,venitaeaglet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wendelking]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hedwigbosenw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mirabellacha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,toddfuggles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nateuvedale]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aindreabrass]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestyndeni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ceceharverso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joshuahdebil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bobbykelby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sashaesler]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vonnycheng]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,antonellajon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nolandguinna]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brendinpawle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,crystievanic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,inezrummery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambytucsell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,timmyferrers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiadorke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rozelladripp]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,abbieklyner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juanajuliano]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,natalyaclinn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carcehowling]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rossiekrollm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berriphillim]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickyfurney]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beatricefonz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,iagosalerno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mellisentwoo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dannyhurdis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tedblaydon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmalynnlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nessieludwik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gilbertinery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gilbertasiby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,whitakerbrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebulensegro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,walthawkyens]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylindascr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fanyawadeson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lisabethscri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,annadianetru]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marchallargi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,remingtonfer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylgunner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cathrynvaiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leawyrill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rudienormanv]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,allissastobb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leftynutkins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,millisentcot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lezleywye]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bjornbaglow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zabrinahelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fawnlea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,abbiesuermei]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,letitiaserra]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eduinotruin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldensnape]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hodgeagglio]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alejandrodud]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leighbartosi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartmelross]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wiltcrotty]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avromsimonea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassondracre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vilhelminadu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sewardkolush]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,regenharvatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raquelabeswe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,franciskuspl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,meggiirce]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,antonellajon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennafeitos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gillavrick]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamiltonfett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thaynebaumai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylouscull]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,washbaudino]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,russmorman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winjohansen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arvcrookes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabieraden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pegeensouthe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickolaineal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,natathreadgo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxyhoundsom]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristoforpar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hodgebails]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliannethew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fredrarigard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,penrodcortes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wardevern]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bettebattrum]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elfierenne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tallielansda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodolpheblac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emelialejean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rozelladripp]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,matthusleipo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,odeledehaile]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeremeroggie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,staciapenlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sapphirakiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loneelaphorn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamishcarles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berniewinspa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christopherr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bethanneprin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jarriddickin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enochmillan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,averillgailo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kienanhemsha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessywestmer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelinawemes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brendishanni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabeysign]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tarynnancarr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chaseosgorby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,phylysherche]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aindreabrass]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pernellgotth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gaelancaldai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,seekeech]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bobbykelby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joryveevers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabieraden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christianato]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robycullon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dulcianawilc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obieairth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ardenchaudre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lymanwand]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sanderschata]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aimeenezey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,felicitycrum]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doriebounds]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melisseeuels]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,caterinapoyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiadorke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liefcuredell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,regenharvatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stephannorth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassondracre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marlineguter]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hodgeagglio]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dulcianawilc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clercyeudall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robbincossan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgeannaba]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kellenevett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcellodalw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,myrtacaldaro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubriepeters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elveraram]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,averilvample]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hobietwelves]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ulrichroskam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doriebounds]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shelbaeppson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marwillshire]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gearardmcrae]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariettadurd]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldemarlint]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,johnnacoffin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,geryormond]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodneyconre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sanderschata]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sutherlandda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldenblacks]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clevelandgro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mellicentpal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suzanngeorge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kenonhowle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeffryloveit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chrotoempowd]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shanoncokely]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,galebettis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,collypendrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hobietwelves]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gustavusbrik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,humbertomord]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gracetracy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chaseosgorby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alandickovic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,homerusfigur]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ryankingswoo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambytucsell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pippopottica]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cornielammim]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliannethew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robbincossan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelinbaudr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shannonhans]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,starrgurry]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,miltonloweth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earlielitchm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marilynscrub]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,layreilingen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mauriefaye]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dolliecallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,archibaldobu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gailclemett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldemarlint]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bjornbaglow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jennifercush]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,silvabudgen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxyhoundsom]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,consolataatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,irajosskovit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lelamostin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cristianmew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariuspeltz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fairhurlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adioakhill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,isaactwinbor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivamelville]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gibbiepegden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittdehmel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aundreadoman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,averillgailo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shanieshawel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tracybatchle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marymcsweene]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tobeolivet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elfierenne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adobabb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,burchshawl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wendypaffot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nanicehebbar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lymanwand]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,araserot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daniellejanu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adobabb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lewshaudfurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristiencher]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jannelwipfle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hashimbullen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,randeesyming]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melanieavery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gibbiepegden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,starrgurry]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,russmorman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,venitaeaglet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassiemcgee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lindjakubski]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bordylyddyar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,drudpharoah]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristinadepi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylouscull]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,josefaputten]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gueneveremai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aimeenezey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,briannemaria]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashieningles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,homerusfigur]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vitoriaberne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,algernonbran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winifielddea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zorinalansle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robinetfawlo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,quintillahol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hedvigbyway]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jodimcduff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tedblaydon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,penrodcortes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,almirewalby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,collypendrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gwendolynian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sidneeferron]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,micvolk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pacokemmett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,skyejonke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,buckiecameli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,frededwards]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,florencebren]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kalilabellan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alastairpelt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebulensegro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vilhelminadu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gannyboldiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leightonstan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berkiedelafo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liannaodeson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carriesauvan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chickyweagen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nicholasdacc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donnicatteri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dinahsheaf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,atlantegowth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earliemclane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sayrecunning]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edgarpriden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gueneveremai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeanahawkesw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlynehache]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,archibaldobu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreamarqui]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartonandras]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brookgarrish]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dorotheefolb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jacindagouch]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,corbetaberha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,estrellitala]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcelloleat]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cariapaul]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylinsenec]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winifielddea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zeligsquibbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,louiseradmer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubreyechell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,issieold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yardgirdwood]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cherrisamson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nissasidebot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rosinalincey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vilhelminadu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arnaldobasil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vitoriaberne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loratomlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salominickle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lukeervine]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,paulymcalind]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sapphirakiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pegeensouthe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,redmazzei]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stormzincke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sosannastear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rahalrosenth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmalynnlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalliddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lelamostin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,annadianetru]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daisiloudian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,burchshawl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,norriehaybal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shellysheldo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cindapipkin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vannieguidon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,violanteanto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zachariasshi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pepillolong]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,merrilymcram]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartmelross]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessikabeddi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derwardchaff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ozzycicerone]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vivianahanha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucillehofto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tatianiarutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittdehmel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,caterinapoyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,welbyzute]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alonzojemiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brendishanni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tobeolivet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestyndeni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvishesbroo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,matteogrigor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucitapriest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jaynemazzia]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,albertojodre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tulleytaters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carmellaludg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faydrastorck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlabeck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beretleathwo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,whitakerbrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,friederikelo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcotomczyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,floydhuie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chadwicknorm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sebastianoke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,remingtonfer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liefcuredell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,olvanhawksle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,karolycoolic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berniewinspa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christabello]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bjornbaglow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,martinapeert]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clemmiegorce]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ulrichroskam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,letitiaserra]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,creighjohann]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryrainy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,worthfaherty]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lamaringlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,symanmoralis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leighbartosi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,candidahulle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vivianahanha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahcompf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,baxterbenedi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beretleathwo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodolpheblac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,valekiffin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joryveevers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jesuslamke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,valekiffin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joreyfleeman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teresaevetts]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arnaldobasil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kendallburli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vinniepavlik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cheridahuric]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickykarolcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sylasgraser]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rogeriogresl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ronnabaynham]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harriotodde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,roxineschnit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rebeccaaxelb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donicaaubray]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garrardrafte]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thornytilber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ariellelopez]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,corbetaberha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,annaleelarve]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lilahmaccree]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,floydhuie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rollinskitca]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ulrichroskam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zanefrushard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teddiemably]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donnicatteri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,goddartbackh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryjoadnam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adejeffress]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreabroken]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,debigiamuzzo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryllound]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carliecuerda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,baxterbenedi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dametomes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,parsifaldean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maximodyott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,margapringle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristoforpar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,watbaldi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pernellgotth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rowenagrayst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murdockdrain]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lylemcgreay]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristilenden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dolliecallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salliesaint]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,antonellajon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chickyweagen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dametomes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,careyvancast]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tishchieze]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marksweeting]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,roxineschnit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mignonnecast]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melanieavery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,millisentcot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hedwigbosenw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,conniebarrab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hewetvoak]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gertrudisket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgettetab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylgunner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luellepetrol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lindjakubski]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carolemauric]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marjnew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,drudpharoah]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elisewhardle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clarettarave]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelemulles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamlinmcgilm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kathlinshack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kittieshanno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylouscull]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alandickovic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hobietwelves]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ainsleegaski]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maynordricar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sylasgraser]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,roxineschnit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,phaidrazacze]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,orrinrae]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,micvolk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,corbetaberha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mignonnecast]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,immanueljaff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aloysiusgow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcelanutbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,buckieruffel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lewshaudfurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alejandrodud]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zeligsquibbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,seekeech]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreashark]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elmoregiorge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emelialejean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eulaliedivin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubreyechell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eldredgeraws]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murialtimny]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madeleneible]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reuvenrosell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,seekeech]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,malissiaston]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thurstoncald]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,parrykulvear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ignatiusgrin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salominickle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudianshri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cristianmew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evaniadevill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earliemclane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,samkrauss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obieairth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jaynemurrthu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,flinnpease]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxgullan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,olvanhawksle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,craggymcnirl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernyblaszcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiakeran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sosannastear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,consolataatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,henryettafra]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,oliarycroft]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winjohansen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,micvolk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aeriellvinal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beckistorr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,skyejonke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adioakhill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,morganwanjek]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,drudpharoah]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hodgebails]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellynnrelfe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chrisbraniff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robycullon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waringskill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,uriahfraylin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelynedobr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edgarpriden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,laurentcolli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cosmodripps]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rabiyanshin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ronnabaynham]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,whitakerbrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alfieseddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariangeaven]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,devinwhyley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luellepetrol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,candigheerha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,keithmaker]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittenyandr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcelloleat]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katharineant]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pernellgotth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorettaginn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jorriedenisk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellynnrelfe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evinplaice]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edythemathis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gailclemett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winjohansen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winifielddea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dovchaunce]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,killysplevin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thornytilber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camellacaine]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farliemcgilv]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evinplaice]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farliemcgilv]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salominickle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcellodalw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennafeitos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliettacarr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rudiegwillim]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jasenbrayson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,patenthrift]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,malissiaston]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marysacamill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lukeervine]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,galebettis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nessieludwik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgettetab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lanarothchil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camalafurnel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,patenthrift]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rikiscarbarr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thaxterschol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,saunchocolle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,whitakerbrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zanefrushard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zachariasshi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adansimm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,florrydegior]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,parrykulvear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georginemacc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michelhazele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spensermacge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgettetab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickykarolcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cacilialipsc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liefcuredell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,darpossa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eduinotruin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zorinalansle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kendallburli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelinbaudr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cesarefrazer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bordylyddyar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucasdevaan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gearardmcrae]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,welbyzute]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheryerooson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestatejer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ozzycicerone]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kendallburli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fredericamac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,romondabrizl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gradygane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avanesey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,manuelrubel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,candigheerha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sewardkolush]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,violettapres]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashleyreadwi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sophiedoming]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tobeolivet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernardodabe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,walliwbartol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernyblaszcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shellysheldo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christabello]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thornytilber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farandchismo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,valekiffin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,devinwhyley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dulcianawilc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudianshri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kienanhemsha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,drudpharoah]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kellyloins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marysacamill]' -p hospital.vt 
