#!/bin/bash
cleos push action hospital.vt delpatient '[hospital.vt,frasierkelme]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorettabeyne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aluinzoppo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,flinnpease]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mirabellacha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beatricefonz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalliddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rabbibleasda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessikabeddi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcellodalw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kittieshanno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reniechallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivamelville]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcilleclew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennafeitos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juninaackroy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hansonrowsel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliettacarr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,janneldecruz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,halsymavin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claretabrida]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lylemcgreay]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wernhercasta]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,keaneaspinal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madlinpetrie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shadowhawtry]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melanieavery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elainacowope]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obadiahcumbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalebifie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yulmajudron]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,manohawker]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tedmundstobb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christopherr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcelloleat]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,burchshawl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doreyantosik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sandimollett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mosshillaby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorilynscoll]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebulensegro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,benjamencutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rollinskitca]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheriedigiac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,haroungligor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,goddardpires]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,baxterorourk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,samkrauss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,henryettafra]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,matthusleipo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,starrgurry]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcelanutbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudettaket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,papagenaspir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berkiedelafo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kierstenfeld]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raquelabeswe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariangeaven]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wendelking]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pincusmariet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,humphreyemin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obadiahcumbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reniechallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camellacaine]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rabbibleasda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,simonyearsle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shandrawellf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cheridacrut]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliannethew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivilibbis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristiencher]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zilviagiffen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,myrtacaldaro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariebramer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlimacian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastingsnapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,washingtonga]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wendelking]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clarettarave]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,humphreyemin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,susyriggulsf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeremeroggie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,remingtonfer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,frededwards]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,noamileopold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldensnape]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grayklampt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pepillolong]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickykarolcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garrettyearn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sophienyland]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,magnumblower]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,layreilingen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,catiemarkham]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gretalsimonn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madalenacurs]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katharineant]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georginemacc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelinbaudr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,skyejonke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lewshaudfurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellynnrelfe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dannyhurdis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelinbaudr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murialtimny]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loriannewane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,glynnisphili]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylgunner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doriebounds]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dolliecallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vladimirburl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,careymckirto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,patenthrift]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,layreilingen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,irajosskovit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessollenbut]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anatolascort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,baxterbenedi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pincasjahns]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madeleneible]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murdockdrain]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcellinaal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obieairth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cospaintain]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claybournegr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,royaldukes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doriveque]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suzanngeorge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emelialejean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,penrodcortes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reamonnshawy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittdehmel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,craggymcnirl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheriedigiac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hedvigbyway]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,theowesson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylaylin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hymanboorn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lelamostin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,heddiebernas]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvanmacias]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgenahart]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zabrinahelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,florindacapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joannebrall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vanbarritt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elainacowope]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,malissiaston]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kaylawildash]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelemulles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leveyhawes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmalynnlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camsuller]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robinetfawlo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robycullon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tedmundstobb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,meggiirce]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yardgirdwood]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shaylynpeter]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,matthusleipo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,albertojodre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nessieludwik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernyblaszcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marysacamill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,koretayspell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ceceharverso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,remingtonfer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reinaldotarn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juanajuliano]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chrisbraniff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,godwinabadam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barronreeks]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cesarefrazer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ariellelopez]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loisebazek]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katalinmaith]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bentleybirne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suttonnixon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ulrickpotzol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joelynnmanse]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melisseeuels]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gaelancaldai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harlinmackle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxyhoundsom]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruddnewall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,watbaldi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,goddardpires]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camalafurnel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avabonicelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bellegianill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessywestmer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,giuliomarle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thelmawoods]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melanieavery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shaylynnhunt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,noraopdenort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sebastianoke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,winjohansen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,consolataatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,frankybaldas]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zelmagirarde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,horatiushuth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sapphirakiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reuvenedgett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickyelias]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliedukelow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claybournesl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,issieold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alandickovic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mitchaelmacr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gradygane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enrikasaket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arlineheeley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylaylin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jariddominig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,betsyverlind]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grannyhalwar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camsuller]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelinbaudr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pepillolong]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,abbiesuermei]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vivianahanha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,litaipsly]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucillehofto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariuspeltz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,herberthunda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,annaleelarve]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,blondellshir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,johnnacoffin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,homerusfigur]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,martinapeert]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmitdillamo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,papagenaspir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorettabeyne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,catherinbawc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cherrisamson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lorilynscoll]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rossiekrollm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gingerstillm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,essielyste]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,almirewalby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jordanafilya]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teddiemably]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,oberonodd]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salominickle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wilonemcllee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daremowatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,giselabranni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wandiecourag]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ysabelketley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,randallsmith]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodneyconre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carmelitapri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derwardchaff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylgunner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vilhelminadu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,royaldukes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,martinapeert]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cesarefrazer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reuvenrosell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,layreilingen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,richartrobot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nadeenpellam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldenblacks]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,opalinahiggo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zorinalansle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wesleyhrihor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kienanhemsha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubreychuck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalebifie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ringhabergha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shanoncokely]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,graystreets]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,killysplevin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reinaldotarn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edgarpriden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luellepetrol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristosedgel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hyattcatteri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tanneyclews]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raquelabeswe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reamonnshawy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lamaringlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayecastaned]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joannaworlan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michelewille]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marilynscrub]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juliettacarr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lewshaudfurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garrettyearn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zeligsquibbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zabrinahelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wardevern]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,horatiofarlh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lelamostin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brucepahlsso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maynordricar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melisseeuels]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hillaryviles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bobinedybald]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gaelancaldai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,theowesson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryjoadnam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shaylynpeter]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thelmawoods]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlingratre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,richartrobot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlingratre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ingedeacock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joreyfleeman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashieningles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waynewykes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalebifie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiakeran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,guselfe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leveyhawes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,graystreets]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,denysferreir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adriahutton]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,albinamartyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,felicitycrum]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,legratonner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evinplaice]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,felicitycrum]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christopherr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tallielansda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sybilbraganz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ysabelketley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jariddominig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arnaldobasil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christalleja]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carcehowling]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obadiahcumbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,betsyverlind]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hodgebails]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raynellstumm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,milogethen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcellinami]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vitoriaberne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beallebevers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,raynellstumm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bellegianill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristosedgel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juditharocki]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,antonellajon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pernellgotth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gustavusbrik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alfieseddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,phylysherche]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastypattins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickolaineal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joannebrall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ingedeacock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carriesauvan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vannieguidon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pincasjahns]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeremeroggie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,benjamencutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jesseechene]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodolpheblac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,renellesolle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wendypaffot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruddnewall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,laylareynard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittenyandr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryrainy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emelialejean]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,iveodonohue]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gradygane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,patenthrift]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxyhoundsom]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cosmodripps]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enrikasaket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daisiloudian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastingsnapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestynacos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastingsnapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spensermacge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,merrilymcram]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anna-dianetr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vladimirburl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bordylyddyar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,royaldukes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,almirewalby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,consolataatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beatricefonz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cherrisamson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alissasperli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,davetadudgeo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvishesbroo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,giuliomarle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kierstenfeld]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ezrajoselevi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vidovictrele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tillywarwick]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,traciepaulil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,redmazzei]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,giorgioreise]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chrotoempowd]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,samkrauss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waringwreath]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adejeffress]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thurstoncald]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ardrareeder]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sutherlanhir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,atlantegowth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donicaaubray]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faulknergeel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeffryloveit]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melindaterne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marksweeting]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,butchcromack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,penrodcortes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,randeesyming]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marrileesimn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elisewhardle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelinbaudr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruddiethorro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vannieguidon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dannyhurdis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eadaglencros]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beatricefonz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evaniadevill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldenblacks]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melanieavery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,inezrummery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zabrinahelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garecasbolt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hollyharrawa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aindreabrass]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ronnabaynham]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,litaipsly]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adobabb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheldenfashi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,catiemarkham]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristinadepi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tremaineedri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hollyharrawa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tarynnancarr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristinadepi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,louiseradmer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvanmacias]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lazaregwin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adansimm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,charleenhatr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,keithmaker]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,noamileopold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christabello]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spensermacge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,briannemaria]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,darmacdonald]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kordulatrene]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sibspelman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rebashugg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgettetab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shelbaeppson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gaelancaldai]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leighbartosi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jacksonrodwe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,watbaldi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joelynnmanse]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yovonndarobi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ramonhulkes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestynacos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shannonhans]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,larisacordob]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marwillshire]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashieningles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamiltonfett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elisabethmou]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elfierenne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pericehiscoc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chrissiechar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grisselwhewa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennafeitos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anamarkova]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aundreadoman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brendishanni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marymcsweene]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doreliabanst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sebastianoke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loratomlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rollinskitca]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aniashillida]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,candigheerha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,theowesson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vannieguidon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,debigiamuzzo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shanoncokely]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,iagosalerno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pippopottica]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessikabeddi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melanieavery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cospaintain]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,paulymcalind]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,goddardpires]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zelmagirarde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rahalrosenth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arviefallanc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pamellastock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barybenton]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avromsimonea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,homerusfigur]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dolliecallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reuvenedgett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,isabeldeblin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelinawemes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sutherlanhir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eldredgeraws]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sanderschata]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ulrichroskam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zondramasure]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leticiadorke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,haroungligor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pierettedike]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,papagenaspir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,linneayushma]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jacksonrodwe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clausgaber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fredericamac]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodgewilmott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ignatiusgrin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,timmyferrers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ronnabaynham]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jocelynedobr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elsiemacalle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juninaackroy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,corneysmyley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreamarqui]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,briannemaria]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dolliecallen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garrardrafte]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loratomlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trixblondin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rudienormanv]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tremaineedri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickolaineal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cariapaul]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryrainy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristiencher]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gilbertinery]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,killysplevin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,garvintyers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,josefaputten]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sebastienell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebulensegro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faulknergeel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,malissiaston]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pearcerosett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fleurkitteri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmalynnlest]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hastypattins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juanajuliano]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sanderschata]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,travisdanaha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sutherlanhir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evelinsertin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickolaineal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spenceomalle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zeligsquibbe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamlinmcgilm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gibbiepegden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,whitakerbrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruddiethorro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nolandguinna]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avabonicelli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harriotodde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barriebaigri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgeannaba]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marylouscull]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yancyturnock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,oberonodd]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickyelias]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evelinepowle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stirlinginga]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,estrellagirs]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clercyeudall]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chickyweagen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreabroken]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,averillgailo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brendinpette]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reuvenedgett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maynordricar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rowlandmerck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayecastaned]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pippopottica]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beatricefonz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayleyschwan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,allissastobb]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melisseeuels]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,obieairth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marvpohlke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,salominickle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murdockdrain]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tytrewhela]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivilibbis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamiltonfett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kesliejudgki]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,friederikelo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambrosmacker]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sosannastear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barthwatchor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vilmaattfiel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liannaodeson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kennedymould]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katecino]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,natalyaclinn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clausgaber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evelinsertin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,estrellitala]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yancyturnock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gibbiepegden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kittieshanno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamiltonfett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bordylyddyar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nadeanworsal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,butchcromack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,madalenacurs]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edythemathis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambrosiusgow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rossiekrollm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamishcarles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pincusmariet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,noraopdenort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,checostley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cathrynvaiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,randymaccurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aeriellvinal]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enriquetamcg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheelabutner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stephanusgoo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,caterinapoyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cosmodripps]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,careymckirto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chadwicknorm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faulknergeel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rogeriogresl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,spenceomalle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,duncantrollo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melisseeuels]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teriannvila]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,floydhuie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rochellatapp]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daisiloudian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beliciasulta]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheryerooson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,franciskuspl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellynnrelfe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cindyofallow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chaseosgorby]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bentleybirne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vannieguidon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nessieludwik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,esmerosenber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vladimirburl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lyssabutterf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donniekinloc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marlineguter]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,debigiamuzzo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shannonhans]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harriotodde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestatejer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nevsafried]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shannonhans]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,devinwhyley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,miltonloweth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alicktetters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yolaneuden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gavshaughnes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brittdehmel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,algernonbran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maximodyott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lyssabutterf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gavshaughnes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,killysplevin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestynacos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,grayklampt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgenahart]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beckistorr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodgewilmott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristosedgel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hansonrowsel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,delcinagrett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marilynscrub]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebulensegro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derwardchaff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,basiliosimpk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pegeensouthe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,haleighlight]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessywestmer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashieningles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,micvolk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,heddiebernas]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aletheacapst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartietreffr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,horatiofarlh]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jehannawethe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernardodabe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carmelitapri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yolaneuden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ashlimacian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elisabethmou]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ysabelketley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,litahunn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pacokemmett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yulmajudron]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arviefallanc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,saunchocolle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gretnachaims]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waldemarlint]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,treforpoplee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassiemcgee]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rosinalincey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lymanwand]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristoforpar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pippopottica]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sonjaboyen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luellepetrol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,camalafurnel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,myrtacaldaro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sophiedoming]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nanicehebbar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,basiliosimpk]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anatolascort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,joreyfleeman]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kordulatrene]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gabrielarrig]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brynaferreo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,annaleelarve]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,barybenton]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,murialtimny]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,donicaaubray]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gibbiepegden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristiencher]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartletandro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,briannemaria]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earlielitchm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leawyrill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kellyceeley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,symanmoralis]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,skyejonke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,demetrigulli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jeanahawkesw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ceciliameeus]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,blondellshir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gannyboldiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,collypendrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sayrecunning]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stephanusgoo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michelewille]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gannyboldiso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,parrykulvear]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvishesbroo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trixblondin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christopherr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,toddfuggles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahcompf]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faemccurley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avismerioth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,magnumblower]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruthannlegon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lelamostin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,melisseeuels]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,archibaldobu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lazaregwin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maryrainy]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jehannawethe]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dorrycoyne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jimgingold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brucepahlsso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sharaislewco]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enochmillan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreashark]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,catherinbawc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stantonmctea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lazarolocard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leftynutkins]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carmellaludg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michelhazele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cariapaul]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,royaldukes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,crystievanic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pincusmariet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faemccurley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marksweeting]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wesleyhrihor]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gretnachaims]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristiencher]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cheridacrut]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayleyschwan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennacoggil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fredrarigard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lucillehofto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harriotodde]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,estrellagirs]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,stephanusgoo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cathrynvaiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katalinmaith]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,richartrobot]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,eamonparkeso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jasenbrayson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wesleyhinken]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fredrarigard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vidovictrele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hildyrosini]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maynordricar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kathlinshack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,debigiamuzzo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,consolataatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marchallargi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,laylareynard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katerinaleve]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,simonyearsle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marlanestutt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,walthawkyens]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elisabethmou]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gingerstillm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,thurstoncald]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristosedgel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faydrastorck]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreamarqui]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgettetab]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doreliabanst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,beallebevers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juietacollin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tandicraiste]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anyaearie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sebastienell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,saunchospitt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,walthawkyens]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,saunchocolle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anatolascort]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vinniepavlik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylgunner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lemarpricket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,charleenhatr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leawyrill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,neallwiley]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ardythdunnaw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cristianmew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,luellepetrol]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nortonyirrel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suttonnixon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maxgullan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kamilahconni]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clausgaber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wandiecourag]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elwirawines]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sashaesler]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ciriloprestn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rodgewilmott]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zanefrushard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rafaelllegru]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,algernonbran]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dianemariebi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tytrewhela]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,juanajuliano]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teddiemably]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marilynscrub]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berniewinspa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gibbyesbrook]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sauveurpache]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rosamondkenw]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariangeaven]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hildyrosini]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,darpossa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dovchaunce]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teriannvila]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,orrinrae]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alicktetters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,layreilingen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,matthusleipo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hamlinmcgilm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,timmyferrers]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loriannewane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,haleighlight]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elmoregiorge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,godwinabadam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daisiloudian]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pearcerosett]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennafeitos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,jessollenbut]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,moyratester]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,katalinmaith]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derrilharbar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hobietwelves]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,monroepedgri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,atlantegowth]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,litaipsly]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,violanteanto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earlegethen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,miguelwheatm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sebastianoke]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,trennafeitos]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambrosmacker]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alexiofumaga]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mariangeaven]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,michalliddon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,daremowatt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hashimbullen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waringskill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cindapipkin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bordylyddyar]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ciriloprestn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lewshaudfurt]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elveraram]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emmalynnesco]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,iagosalerno]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,edgarpriden]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pepillolong]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cherrisamson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,morganwanjek]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,humbertomord]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,martinapeert]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nolandguinna]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambrosiusgow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rogeriogresl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nickyfurney]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,royaldukes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earliemclane]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,victoriabart]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bartletandro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,valekiffin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leelahobreen]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,romondabrizl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,venitaeaglet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kirbydudenie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,genemateescu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,homerusfigur]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maudgosnold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,addyoliveto]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tallielansda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chadwicknorm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,toddfuggles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,christabello]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aluinzoppo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aloysiusgow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zorinalansle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zedmaccome]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liannaodeson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheldenfashi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,berriphillim]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,liefcuredell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sapphirakiss]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vidovictrele]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ruddiethorro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pavlaspyking]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,florindacapo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreamarqui]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celindabemlo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,valmarichie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yancyturnock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claybournesl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,elmoregiorge]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hewetvoak]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lylemcgreay]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,gingerstillm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,karolycoolic]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,victoriabart]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,frededwards]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ezrajoselevi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,josefaputten]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,starrgurry]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bentleybirne]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheryerooson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ariellelopez]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,redmazzei]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evelinepowle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carmellaludg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,sheelabutner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,redmazzei]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waynewykes]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carmellockwo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,genemateescu]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,avromsimonea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brynaferreo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,enriquetamcg]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waringwreath]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,evinplaice]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wendelking]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudettaket]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,traciepaulil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claudianshri]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cindyofallow]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,magnumblower]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zedmaccome]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,faulknergeel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,floydhuie]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,theowesson]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,wardevern]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,clarinemchal]' -p hospital.vt 
