#!/bin/bash
cleos push action hospital.vt delpatient '[hospital.vt,iorgobilovus]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,traciepaulil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,henryettafra]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marcellinami]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ambytucsell]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,robbincossan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doreliabanst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arieglynn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andreabroken]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,reinaldotarn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,suttonnixon]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,saunchocolle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,emlentunnock]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,candigheerha]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anamarkova]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,olvanhawksle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farandchismo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,lulubourton]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,doreyantosik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kenonhowle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,marwillshire]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,collypendrid]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassondracre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,andrewchoffi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yovonndarobi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,baxterbenedi]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,claybournegr]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kayecastaned]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,harlinmackle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leightonstan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cheridahuric]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kearneyfearn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aubriepeters]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,celestatejer]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,romondabrizl]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,albinamartyn]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,odeledehaile]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,dosirandalst]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,shanieshawel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,laurentcolli]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hollyharrawa]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,issieold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rivamelville]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cirilobwye]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zanefrushard]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,vinniepavlik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,herberthunda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,chloecharle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,denysferreir]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ignatiusgrin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,georgeannaba]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,teddiemably]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,patenthrift]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,maudgosnold]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,abbieklyner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,frasierkelme]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,esmerosenber]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ellsworthhan]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cacilialipsc]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,legratonner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hodgeagglio]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,alvishesbroo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,butchcromack]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bellegianill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ceceharverso]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tallielansda]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,carylgunner]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,myrtacaldaro]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yulmajudron]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,zebedeedorew]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,earlielitchm]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,adelemulles]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tracybatchle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cosmodripps]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,waringwreath]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,bernyblaszcz]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,loratomlin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,leawyrill]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,kristosedgel]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,fawnlea]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,anamarkova]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nadeenpellam]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,seekeech]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,farliemcgilv]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,derwardchaff]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cassondracre]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,pincusmariet]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,mignonnecast]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,brendinpette]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,friederikelo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,aluinzoppo]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,arnaldobasil]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,tracybatchle]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,yulmajudron]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,cheridacrut]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,rosinalincey]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,nessieludwik]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,ignatiusgrin]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,meggiirce]' -p hospital.vt 
cleos push action hospital.vt delpatient '[hospital.vt,hansonrowsel]' -p hospital.vt 
